### ISSUE TITLE
add examples of general workflow and plotting

### ISSUE THREAD

**Issue by ahelm** [GoLP-IST/nata#23]
add some or at least one example about working with `nata`

**Comment by fabiocruz** [comment]
This should have associated Binder links.

**Comment by fabiocruz** [comment]
This is now being done and released together with new versions of the APIs. Since this was a general issue, I am closing it. It still applies to new developments (e.g. plugins), but this is now considered a necessary step of the development, and as such it should be provided by default. If examples are missing for a particular feature, a new specific issue should be opened.
